FROM node:22-bookworm-slim

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.17.1 --activate

ARG VITE_CONVEX_URL
ARG VITE_AUTH_ISSUER
ARG VITE_AUTH_CLIENT_ID
ARG VITE_AUTH_AUDIENCE
ARG VITE_AUTH_REDIRECT_URI
ARG VITE_AUTH_POST_LOGOUT_REDIRECT_URI

ENV VITE_CONVEX_URL=$VITE_CONVEX_URL
ENV VITE_AUTH_ISSUER=$VITE_AUTH_ISSUER
ENV VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID
ENV VITE_AUTH_AUDIENCE=$VITE_AUTH_AUDIENCE
ENV VITE_AUTH_REDIRECT_URI=$VITE_AUTH_REDIRECT_URI
ENV VITE_AUTH_POST_LOGOUT_REDIRECT_URI=$VITE_AUTH_POST_LOGOUT_REDIRECT_URI

COPY package.json ./
COPY insightful-property-hub/package*.json ./insightful-property-hub/
RUN npm install
RUN npm install --prefix insightful-property-hub

COPY . .

RUN npm run build:web
RUN npm run build:mastra

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV MASTRA_HOST=0.0.0.0
ENV MASTRA_PORT=4111
ENV MASTRA_CHAT_URL=http://127.0.0.1:4111/chat
ENV MASTRA_OKF_CHAT_URL=http://127.0.0.1:4111/chat/okf
ENV MASTRA_FACEBOOK_MARKETPLACE_CHAT_URL=http://127.0.0.1:4111/chat/facebook-marketplace

EXPOSE 3000 4111

CMD ["npm", "run", "start:platform"]
