/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalClientSlugRouteImport } from './routes/portal.$clientSlug'
import { Route as ApiModelsRouteImport } from './routes/api.models'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSourcingRouteImport } from './routes/_app.sourcing'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPropertiesRouteImport } from './routes/_app.properties'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppLeasesRouteImport } from './routes/_app.leases'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as PortalClientSlugIndexRouteImport } from './routes/portal.$clientSlug.index'
import { Route as PortalClientSlugTeamRouteImport } from './routes/portal.$clientSlug.team'
import { Route as AppPropertiesIdRouteImport } from './routes/_app.properties.$id'
import { Route as AppLeasesIdRouteImport } from './routes/_app.leases.$id'
import { Route as AppDocumentsIdRouteImport } from './routes/_app.documents.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'
import { Route as AppAutomationsIdRouteImport } from './routes/_app.automations.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalClientSlugRoute = PortalClientSlugRouteImport.update({
  id: '/portal/$clientSlug',
  path: '/portal/$clientSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcingRoute = AppSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppLeasesRoute = AppLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const PortalClientSlugIndexRoute = PortalClientSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalClientSlugRoute,
} as any)
const PortalClientSlugTeamRoute = PortalClientSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PortalClientSlugRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppLeasesIdRoute = AppLeasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeasesRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppAutomationsIdRoute = AppAutomationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/automations': typeof AppAutomationsRouteWithChildren
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/invoices': typeof AppInvoicesRoute
  '/leases': typeof AppLeasesRouteWithChildren
  '/organizations': typeof AppOrganizationsRoute
  '/properties': typeof AppPropertiesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/search': typeof AppSearchRoute
  '/sourcing': typeof AppSourcingRoute
  '/tasks': typeof AppTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/portal/$clientSlug': typeof PortalClientSlugRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/automations/$id': typeof AppAutomationsIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/leases/$id': typeof AppLeasesIdRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/portal/$clientSlug/team': typeof PortalClientSlugTeamRoute
  '/portal/$clientSlug/': typeof PortalClientSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/automations': typeof AppAutomationsRouteWithChildren
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/invoices': typeof AppInvoicesRoute
  '/leases': typeof AppLeasesRouteWithChildren
  '/organizations': typeof AppOrganizationsRoute
  '/properties': typeof AppPropertiesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/search': typeof AppSearchRoute
  '/sourcing': typeof AppSourcingRoute
  '/tasks': typeof AppTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/portal': typeof PortalIndexRoute
  '/automations/$id': typeof AppAutomationsIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/leases/$id': typeof AppLeasesIdRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/portal/$clientSlug/team': typeof PortalClientSlugTeamRoute
  '/portal/$clientSlug': typeof PortalClientSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/automations': typeof AppAutomationsRouteWithChildren
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/leases': typeof AppLeasesRouteWithChildren
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/properties': typeof AppPropertiesRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/sourcing': typeof AppSourcingRoute
  '/_app/tasks': typeof AppTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/portal/$clientSlug': typeof PortalClientSlugRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/_app/automations/$id': typeof AppAutomationsIdRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/leases/$id': typeof AppLeasesIdRoute
  '/_app/properties/$id': typeof AppPropertiesIdRoute
  '/portal/$clientSlug/team': typeof PortalClientSlugTeamRoute
  '/portal/$clientSlug/': typeof PortalClientSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/automations'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/invoices'
    | '/leases'
    | '/organizations'
    | '/properties'
    | '/reports'
    | '/search'
    | '/sourcing'
    | '/tasks'
    | '/api/chat'
    | '/api/models'
    | '/portal/$clientSlug'
    | '/portal/'
    | '/automations/$id'
    | '/clients/$id'
    | '/documents/$id'
    | '/leases/$id'
    | '/properties/$id'
    | '/portal/$clientSlug/team'
    | '/portal/$clientSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/automations'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/invoices'
    | '/leases'
    | '/organizations'
    | '/properties'
    | '/reports'
    | '/search'
    | '/sourcing'
    | '/tasks'
    | '/api/chat'
    | '/api/models'
    | '/portal'
    | '/automations/$id'
    | '/clients/$id'
    | '/documents/$id'
    | '/leases/$id'
    | '/properties/$id'
    | '/portal/$clientSlug/team'
    | '/portal/$clientSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/automations'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/invoices'
    | '/_app/leases'
    | '/_app/organizations'
    | '/_app/properties'
    | '/_app/reports'
    | '/_app/search'
    | '/_app/sourcing'
    | '/_app/tasks'
    | '/api/chat'
    | '/api/models'
    | '/portal/$clientSlug'
    | '/portal/'
    | '/_app/automations/$id'
    | '/_app/clients/$id'
    | '/_app/documents/$id'
    | '/_app/leases/$id'
    | '/_app/properties/$id'
    | '/portal/$clientSlug/team'
    | '/portal/$clientSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiModelsRoute: typeof ApiModelsRoute
  PortalClientSlugRoute: typeof PortalClientSlugRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$clientSlug': {
      id: '/portal/$clientSlug'
      path: '/portal/$clientSlug'
      fullPath: '/portal/$clientSlug'
      preLoaderRoute: typeof PortalClientSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sourcing': {
      id: '/_app/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AppSourcingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties': {
      id: '/_app/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leases': {
      id: '/_app/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AppLeasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$clientSlug/': {
      id: '/portal/$clientSlug/'
      path: '/'
      fullPath: '/portal/$clientSlug/'
      preLoaderRoute: typeof PortalClientSlugIndexRouteImport
      parentRoute: typeof PortalClientSlugRoute
    }
    '/portal/$clientSlug/team': {
      id: '/portal/$clientSlug/team'
      path: '/team'
      fullPath: '/portal/$clientSlug/team'
      preLoaderRoute: typeof PortalClientSlugTeamRouteImport
      parentRoute: typeof PortalClientSlugRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/_app/leases/$id': {
      id: '/_app/leases/$id'
      path: '/$id'
      fullPath: '/leases/$id'
      preLoaderRoute: typeof AppLeasesIdRouteImport
      parentRoute: typeof AppLeasesRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/automations/$id': {
      id: '/_app/automations/$id'
      path: '/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AppAutomationsIdRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
  }
}

interface AppAutomationsRouteChildren {
  AppAutomationsIdRoute: typeof AppAutomationsIdRoute
}

const AppAutomationsRouteChildren: AppAutomationsRouteChildren = {
  AppAutomationsIdRoute: AppAutomationsIdRoute,
}

const AppAutomationsRouteWithChildren = AppAutomationsRoute._addFileChildren(
  AppAutomationsRouteChildren,
)

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppDocumentsRouteChildren {
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsIdRoute: AppDocumentsIdRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppLeasesRouteChildren {
  AppLeasesIdRoute: typeof AppLeasesIdRoute
}

const AppLeasesRouteChildren: AppLeasesRouteChildren = {
  AppLeasesIdRoute: AppLeasesIdRoute,
}

const AppLeasesRouteWithChildren = AppLeasesRoute._addFileChildren(
  AppLeasesRouteChildren,
)

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRouteWithChildren
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLeasesRoute: typeof AppLeasesRouteWithChildren
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSourcingRoute: typeof AppSourcingRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRouteWithChildren,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLeasesRoute: AppLeasesRouteWithChildren,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSourcingRoute: AppSourcingRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalClientSlugRouteChildren {
  PortalClientSlugTeamRoute: typeof PortalClientSlugTeamRoute
  PortalClientSlugIndexRoute: typeof PortalClientSlugIndexRoute
}

const PortalClientSlugRouteChildren: PortalClientSlugRouteChildren = {
  PortalClientSlugTeamRoute: PortalClientSlugTeamRoute,
  PortalClientSlugIndexRoute: PortalClientSlugIndexRoute,
}

const PortalClientSlugRouteWithChildren =
  PortalClientSlugRoute._addFileChildren(PortalClientSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiModelsRoute: ApiModelsRoute,
  PortalClientSlugRoute: PortalClientSlugRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
